services:
  postgres:
    image: postgres:17
    container_name: dbt_tutorial
    environment:
      POSTGRES_USER: dbt_tutorial
      POSTGRES_PASSWORD: dbt_tutorial
      POSTGRES_DB: dbt_tutorial
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:

